version: '3.9'

services:
  db:
    image:
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    image: django-docker:0.0.1
    build: .
    command: 'python3 manage.py runserver'
    ports:
      - "8000:8000"