# Generated by Django 3.2.9 on 2021-11-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_platform', '0003_alter_payloaddevice_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payloaddevice',
            name='device_id',
        ),
    ]
